version: "3"
services:
  portofolio:
    image: tudorneagu90/portofolio:latest
    container_name: portofolio
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
