version: "3"
services:
  nginx-proxy:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: nginx_proxy_manager
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    networks:
      - nginx-proxy
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - /app/portofolio-cosmin/photos:/app/portofolio-cosmin/photos  # Add this line

networks:
  nginx-proxy:
    external: true
