version: "3"
services:
  Portofolio:
    image: tudorneagu90/portofolio:latest
    container_name: portofolio
    expose:
      - "80"
    networks:
      - nginx-proxy
    environment:
      VIRTUAL_HOST: tudorneagu.com
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: tudorneagu.com
      LETSENCRYPT_EMAIL: neagu.t@gmail.com

networks:
  nginx-proxy:
    external: true
