- name: Deploy to VPS
  env:
    HOST: ${{ secrets.HOST }}
    USER: ${{ secrets.USER }}
    PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    APP_DIR: "/app/portofolio"

  run: |
    echo "$PRIVATE_KEY" > /tmp/deploy_key
    chmod 600 /tmp/deploy_key

    # Create directory and clean old files
    ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no $USER@$HOST \
      "mkdir -p $APP_DIR && rm -f $APP_DIR/docker-compose.yml"

    # Copy docker-compose.yml to VPS
    scp -i /tmp/deploy_key -o StrictHostKeyChecking=no \
      ./docker-compose.yml \
      $USER@$HOST:$APP_DIR/docker-compose.yml

    # Deploy the application (with cleanup and orphan removal)
    ssh -i /tmp/deploy_key -o StrictHostKeyChecking=no $USER@$HOST \
      "cd $APP_DIR && docker compose down && docker compose up -d --remove-orphans"
